# Use a base image
FROM Asteroid-game-clone:baseImage

# Set the working directory inside the container
WORKDIR /app

# Copy files from your project into the container
COPY . /app

# Define any necessary environment variables
ENV VARIABLE_NAME=value

# Run any setup or build commands
RUN command-to-install-dependencies

# Define the command to run when the container starts
CMD ["command-to-start-your-application"]
